import os
import smtplib
import logging
from datetime import date, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pandas as pd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()
log = logging.getLogger(__name__)

engine = create_engine(os.environ["DATABASE_URL"])


def generate_weekly_report() -> str:
    """Build a simple HTML report for the past 7 days."""
    week_end   = date.today() - timedelta(days=1)
    week_start = week_end - timedelta(days=6)

    with engine.connect() as conn:
        df = pd.read_sql(text("""
            SELECT city,
                   ROUND(AVG(avg_temp)::NUMERIC,1)  AS avg_temp,
                   ROUND(MIN(min_temp)::NUMERIC,1)  AS min_temp,
                   ROUND(MAX(max_temp)::NUMERIC,1)  AS max_temp,
                   ROUND(SUM(total_rain)::NUMERIC,1) AS total_rain,
                   SUM(CASE WHEN total_rain > 0.1 THEN 1 ELSE 0 END) AS rainy_days
            FROM gold.daily_summary
            WHERE summary_date BETWEEN :s AND :e
            GROUP BY city ORDER BY city
        """), conn, params={"s": week_start, "e": week_end})

    rows = "".join(
        f"<tr><td><b>{r.city}</b></td>"
        f"<td>{r.avg_temp}°C</td>"
        f"<td>{r.min_temp}°C</td>"
        f"<td>{r.max_temp}°C</td>"
        f"<td>{r.total_rain} mm</td>"
        f"<td>{int(r.rainy_days)} days</td></tr>"
        for r in df.itertuples()
    )

    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:600px;margin:auto">
      <h2 style="color:#1a237e">🌦️ Kenya Weather — Weekly Report</h2>
      <p>Week: <b>{week_start}</b> to <b>{week_end}</b></p>
      <table border="1" cellpadding="8" cellspacing="0" width="100%"
             style="border-collapse:collapse">
        <thead style="background:#1a237e;color:white">
          <tr><th>City</th><th>Avg</th><th>Min</th><th>Max</th>
              <th>Rain</th><th>Rainy Days</th></tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="font-size:11px;color:#888;margin-top:20px">
        Generated by Weather Data Warehouse · Open-Meteo · PostgreSQL
      </p>
    </body></html>
    """


def send_email_report(recipients: list[str]) -> None:
    """Send the weekly HTML report by email."""
    html = generate_weekly_report()
    end  = date.today() - timedelta(days=1)

    msg            = MIMEMultipart("alternative")
    msg["Subject"] = f"Kenya Weather Report — week ending {end}"
    msg["From"]    = os.environ["SMTP_USER"]
    msg["To"]      = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP(os.environ["SMTP_HOST"], int(os.environ.get("SMTP_PORT", 587))) as s:
        s.starttls()
        s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASSWORD"])
        s.sendmail(os.environ["SMTP_USER"], recipients, msg.as_string())

    log.info("Weekly report sent to %s", recipients)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    # Print the HTML to terminal (for testing)
    print(generate_weekly_report())